grille:

  niveaux: [
    {nom: Excellent, maximum: 100, minimum: 90},
    {nom: Très bien, maximum: 89, minimum: 80},
    {nom: Bien, maximum: 79, minimum: 70},
    {nom: Passable, maximum: 69, minimum: 60},
    {nom: Insuffisant, maximum: 59, minimum: 0}
  ]

  évaluation:

    nom: 

    total: 100

    précision du total: 0

    pas pour inférence des points: 1

    descripteurs par défaut:
    - Aucune erreur notable.
    - Quelques erreurs mineures.
    - Une erreur significative.
    - Plusieurs erreurs significatives.
    - Lacunes importantes ou travail incomplet.

    critères:

    - critère: 

      total: 

      indicateurs:

      - indicateur: 
        points: 
        descripteurs:
        - Aucune erreur notable.
        - Quelques erreurs mineures.
        - Une erreur significative.
        - Plusieurs erreurs significatives.
        - Lacunes importantes ou travail incomplet.

      - indicateur: 

      - indicateur: 

    - critère:

      total: 

      indicateurs:

      - indicateur: 

      - indicateur: 

      - indicateur: 

  format:

    orientation: paysage # portrait ou paysage

    afficher les points des indicateurs: false

    largeur des colonnes: []

    largeur des colonnes avec commentaires: []

étudiants: