grille:

  évaluation:

    nom: 

    cours: 

  niveaux précision: 1

  niveaux: [
    {nom: "Excellent", maximum: 100, minimum: 90, valeur par défaut: 100},
    {nom: "Très bien", maximum: 89, minimum: 80, valeur par défaut: 85},
    {nom: "Bien", maximum: 79, minimum: 70, valeur par défaut: 70},
    {nom: "Passable", maximum: 69, minimum: 60, valeur par défaut: 60},
    {nom: "Insuffisant", maximum: 59, minimum: 0, valeur par défaut: 30}
  ]


  descripteurs par défaut:
  - "Aucune erreur notable."
  - "Quelques erreurs mineures."
  - "Une erreur significative."
  - "Plusieurs erreurs significatives."
  - "Lacunes importantes ou travail incomplet."

  critères:

  - critère: 

    pourcentage: 

    indicateurs:

    - nom: 

    - nom: 

    - nom: 

  - critère:

    pourcentage: 

    indicateurs:

    - nom: 

    - nom: 

    - nom: 

  format:

    orientation: paysage # portrait ou paysage

    afficher le pourcentage des indicateurs: false

    largeur des colonnes: []

    largeur des colonnes avec commentaires: []

étudiants: